version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bfrpg_user:bfrpg_password@db:5432/bfrpg_mud
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bfrpg_user
      - POSTGRES_PASSWORD=bfrpg_password
      - POSTGRES_DB=bfrpg_mud
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bfrpg_user -d bfrpg_mud"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 