"""Initial schema with PostgreSQL best practices

Revision ID: a7a0a0e31123
Revises:
Create Date: 2025-04-19 15:20:22.997886

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7a0a0e31123"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_areas_id"), "areas", ["id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "item_type",
            sa.Enum(
                "WEAPON",
                "ARMOR",
                "SHIELD",
                "POTION",
                "SCROLL",
                "WAND",
                "RING",
                "AMULET",
                "TOOL",
                "CONTAINER",
                "CLOTHING",
                "FOOD",
                "MISCELLANEOUS",
                name="itemtype",
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("is_equippable", sa.Boolean(), nullable=True),
        sa.Column("equip_slot", sa.String(), nullable=True),
        sa.Column("damage", sa.String(), nullable=True),
        sa.Column("armor_class", sa.Integer(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_table(
        "npcs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "npc_type",
            sa.Enum(
                "VILLAGER",
                "MERCHANT",
                "GUARD",
                "NOBLE",
                "MONSTER",
                "QUEST_GIVER",
                name="npctype",
            ),
            nullable=False,
        ),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("hit_points", sa.Integer(), nullable=True),
        sa.Column("armor_class", sa.Integer(), nullable=True),
        sa.Column("is_hostile", sa.Boolean(), nullable=True),
        sa.Column("dialogue", sa.JSON(), nullable=True),
        sa.Column("inventory", sa.JSON(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("dialogs", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_npcs_id"), "npcs", ["id"], unique=False)
    op.create_index(op.f("ix_npcs_name"), "npcs", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("reset_token", sa.String(), nullable=True),
        sa.Column("reset_token_expiry", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column(
            "race",
            sa.Enum("HUMAN", "DWARF", "ELF", "HALFLING", name="characterrace"),
            nullable=False,
        ),
        sa.Column(
            "character_class",
            sa.Enum(
                "FIGHTER",
                "CLERIC",
                "MAGIC_USER",
                "THIEF",
                "FIGHTER_MAGIC_USER",
                "MAGIC_USER_THIEF",
                name="characterclass",
            ),
            nullable=False,
        ),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("intelligence", sa.Integer(), nullable=False),
        sa.Column("wisdom", sa.Integer(), nullable=False),
        sa.Column("dexterity", sa.Integer(), nullable=False),
        sa.Column("constitution", sa.Integer(), nullable=False),
        sa.Column("charisma", sa.Integer(), nullable=False),
        sa.Column("hit_points", sa.Integer(), nullable=False),
        sa.Column("armor_class", sa.Integer(), nullable=True),
        sa.Column("equipment", sa.JSON(), nullable=True),
        sa.Column("inventory", sa.JSON(), nullable=True),
        sa.Column("gold", sa.Integer(), nullable=True),
        sa.Column("languages", sa.String(), nullable=True),
        sa.Column("save_death_ray_poison", sa.Integer(), nullable=True),
        sa.Column("save_magic_wands", sa.Integer(), nullable=True),
        sa.Column("save_paralysis_petrify", sa.Integer(), nullable=True),
        sa.Column("save_dragon_breath", sa.Integer(), nullable=True),
        sa.Column("save_spells", sa.Integer(), nullable=True),
        sa.Column("special_abilities", sa.JSON(), nullable=True),
        sa.Column("spells_known", sa.JSON(), nullable=True),
        sa.Column("thief_abilities", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "room_type",
            sa.Enum(
                "TOWN",
                "DUNGEON",
                "WILDERNESS",
                "CAVE",
                "FOREST",
                "MOUNTAIN",
                "WATER",
                "BUILDING",
                "SPECIAL",
                name="roomtype",
            ),
            nullable=False,
        ),
        sa.Column("x", sa.Integer(), nullable=True),
        sa.Column("y", sa.Integer(), nullable=True),
        sa.Column("z", sa.Integer(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=True),
        sa.Column("exits", sa.JSON(), nullable=True),
        sa.Column("is_dark", sa.Boolean(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=False)
    op.create_table(
        "character_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("x", sa.Integer(), nullable=True),
        sa.Column("y", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_locations_id"), "character_locations", ["id"], unique=False
    )
    op.create_table(
        "command_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_history_id"), "command_history", ["id"], unique=False
    )
    op.create_table(
        "hirelings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("character_class", sa.String(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column(
            "loyalty",
            sa.Enum(
                "DISLOYAL",
                "RELUCTANT",
                "NEUTRAL",
                "LOYAL",
                "FANATIC",
                name="loyaltylevel",
            ),
            nullable=True,
        ),
        sa.Column("wage", sa.Integer(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("last_payment_date", sa.DateTime(), nullable=True),
        sa.Column("days_unpaid", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("master_id", sa.Integer(), nullable=True),
        sa.Column(
            "hireling_type",
            sa.Enum(
                "PORTER",
                "MERCENARY",
                "SAGE",
                "HEALER",
                "GUIDE",
                "SPECIALIST",
                name="hirelingtype",
            ),
            nullable=False,
        ),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("payment_due", sa.Integer(), nullable=True),
        sa.Column("payment_rate", sa.Integer(), nullable=True),
        sa.Column("payment_last_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hirelings_id"), "hirelings", ["id"], unique=False)
    op.create_index(op.f("ix_hirelings_name"), "hirelings", ["name"], unique=False)
    op.create_table(
        "room_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_room_items_id"), "room_items", ["id"], unique=False)
    op.create_table(
        "room_npcs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("npc_id", sa.Integer(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_room_npcs_id"), "room_npcs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_npcs_id"), table_name="room_npcs")
    op.drop_table("room_npcs")
    op.drop_index(op.f("ix_room_items_id"), table_name="room_items")
    op.drop_table("room_items")
    op.drop_index(op.f("ix_hirelings_name"), table_name="hirelings")
    op.drop_index(op.f("ix_hirelings_id"), table_name="hirelings")
    op.drop_table("hirelings")
    op.drop_index(op.f("ix_command_history_id"), table_name="command_history")
    op.drop_table("command_history")
    op.drop_index(op.f("ix_character_locations_id"), table_name="character_locations")
    op.drop_table("character_locations")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_npcs_name"), table_name="npcs")
    op.drop_index(op.f("ix_npcs_id"), table_name="npcs")
    op.drop_table("npcs")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_areas_id"), table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
